#首页导航



-
  text: '首页'
  controller: 'index'
  action: 'index'
  children:
    -
      text: '子项目'
      controller: 'index'
      action: 'index'
    -
      text: '子项目'
      controller: 'index'
      action: 'index'
    -
      text: '子项目'
      controller: 'index'
      action: 'index'
-
  text: '无子代'
  controller: 'index'
  action: 'index'
-
  text: '父项目'
  controller: 'index'
  action: 'index'
  children:
      -
        text: '子项目'
        controller: 'index'
        action: 'index'
